### ISSUE TITLE
18.10 - External monitors not working

### ISSUE THREAD

**Issue by RobertRozic** [kfechter/LegionY530Ubuntu#32]
Hello,
At first i was using 18.04 and external monitors didn't work even after installing nvidia-390, new kernel etc.
I switched to 18.10 and it started working ( after fresh install ). I was using 2 external monitors, one on HDMI and other one on type C connector. 
After i switched to intel profile using prime-select to save power since i was not using external monitors, then switched back to nvidia my external monitors stopped working.

I am on 4.20.10-042010-generic kernel and nvidia-415 drivers
There is no xorg.conf in /etc/X11/

I solved it using lightdm display manager as suggested, but i am interested why it is not working with gdm3 since it used to work before.

Thank you

**Comment by kfechter** [comment]
After switching back to nvidia, did you try logging out and back in or rebooting?

**Comment by Rox-** [comment]
Yes i did, even reboot... Nothing happened

**Comment by kfechter** [comment]
I have external monitors working on 18.04. I installed nvidia-driver-415 instead of 390, and have kernel 4.20 installed. It took a reboot after switching, and it bugged out for a second, but they seem to work now. There are probably some bugs in GDM around multi monitors.

**Comment by kfechter** [comment]
IIRC, several people also had issues with the 390 drivers and multi-monitors

**Comment by M-Abozaid** [comment]
I'm having the same Issue, my external display is not detected even with lightdm and nvidia-driver-415
i'm using kernel 4.20.10

**Comment by kfechter** [comment]
sudo prime-select nvidia && sudo reboot worked for me when it wouldn't detect my monitor. 

it could also be a bug in xorg or the nvidia drivers, or that combination of installed items on 18.10. I had way more issues with getting 18.10 to work properly, which is why the guide now focuses on 18.04.x LTS.

**Comment by M-Abozaid** [comment]
Prime profile is already set to nvidia, and I'm using ubuntu 18.04 LTS

**Comment by kfechter** [comment]
Is it throwing any errors in dmesg? 

Without having any kind of errors logged, it's extremely difficult to pin down driver issues.

**Comment by M-Abozaid** [comment]
I'm sorry but how can I view dmesg :)

**Comment by kfechter** [comment]
open a terminal and run dmesg. 

you can also pipe into grep if you want to look for specific text

for example 
dmesg | grep nvidia
dmesg | grep prime

**Comment by kfechter** [comment]
I do not recall if dmesg requires sudo. I don't believe it does

**Comment by M-Abozaid** [comment]
dmesg | grep nvidia
dmesg | grep prime
both return nothing :|

**Comment by kfechter** [comment]
hmmm. that means that the nvidia drivers and prime aren't throwing any errors. 

I hate it when there aren't errors, makes everything more difficult. 

Did you upgrade the kernel before or after the nvidia drivers were installed?

**Comment by M-Abozaid** [comment]
What's frustrating is that it was working fine after installation

**Comment by M-Abozaid** [comment]
Yes

**Comment by M-Abozaid** [comment]
I updated to 4.20.11 and I didn't work since then

**Comment by kfechter** [comment]
hmm. its possible that the nvidia module borked on dkms. 

try to reinstall the nvidia drivers with the below command

sudo apt install --reinstall nvidia-driver-415 nvidia-prime

**Comment by kfechter** [comment]
I didn't realize 4.20.11 was out. It's possible that that version broke something as well. It's not entirely uncommon to see point releases of a kernel break something that worked previously. since ubuntu doesn't normally remove old kernel installs, you could also select the older kernel by pressing esc at the purple screen and selecting "Advanced options for ubuntu"

**Comment by M-Abozaid** [comment]
Yes I did that I even uninstalled 4.20.11
Didn't help 
BTW It was working earlier with nvidia-90

**Comment by M-Abozaid** [comment]
Thanks a lot for you help

**Comment by kfechter** [comment]
no problem. I switched back to windows temporarily, but I can try 18.04 again with 4.20.11 and see if I can reproduce.

**Comment by kfechter** [comment]
switching kernels is always risky, that's why my hope is that 18.04.3 will ship with a kernel that already has the module fix.

**Comment by M-Abozaid** [comment]
I was wondering why do you recommend nvidia-driver-415  despite according to this [this](https://www.nvidia.com/download/driverResults.aspx/138919/en-us) it doesn't support gtx 1050ti 

What I'm I missing

**Comment by kfechter** [comment]
That's the quadro specific driver. the Linux 415 series nvidia driver supports nvidia GPUs from 600 series up to the new 20 Series RTX cards. 

"GeForce 600/700/800/900/10 series cards works with 390.xx, 410.xx and 415.xx nVidia drivers"

**Comment by kfechter** [comment]
https://www.nvidia.com/download/driverResults.aspx/141300/en-us

**Comment by M-Abozaid** [comment]
Got it 😄
one thing I noticed though is that when I open Nvidia x server settings I don't see the multi-display settings anymore, it only shows the Prime profile options

**Comment by popvladaurel** [comment]
Hey, I can confirm that nvidia-driver-415 works fine with kernel 4.20.6. I'm running elementary OS 5.0 at the moment, but it's built on Ubuntu 18.04. Still have to reboot to switch between prime prime profiles though...

![nvidia](https://user-images.githubusercontent.com/23455688/53283388-49676380-374e-11e9-8d8b-657921ccbd63.png)

**Comment by M-Abozaid** [comment]
![image](https://user-images.githubusercontent.com/23200283/53285715-7d518180-376c-11e9-9fe3-e51c6358dac2.png)
I've tried multiple kernels and this is how x server settings looks like

**Comment by Rox-** [comment]
I have external monitors working with 4.20.11 and lightdm + nvidia-415
with gdm3 it isnt working

**Comment by kfechter** [comment]
@M-Abozaid That screenshot shows that it is in Intel mode. it won't show any of the nvidia settings other than prime profile if it is in power saving. if switching to nvidia and rebooting isn't helping, then something has gone wrong with the install and it is stuck in intel mode.

**Comment by kfechter** [comment]
I have multi display working with nvidia-driver-415 and kernel 4.20.12. however, I installed the driver after upgrading the kernel, so its possible that DKMS isn't working and the driver is breaking with the kernel upgrade. 

![screenshot from 2019-02-24 00-03-13](https://user-images.githubusercontent.com/4164101/53295366-cda9fd00-37c7-11e9-9214-49dd04edbb59.png)

**Comment by M-Abozaid** [comment]
I'm able to switch to Nvidia (performance mode) but it makes no difference

**Comment by kfechter** [comment]
something is corrupt on the install then. my guess is upgrading the kernel after the modules were installed put everything in a bad state.

**Comment by M-Abozaid** [comment]
I had to reinstall everything :(...
it's working now with kernel 4.20.10, nvidia-driver-415, and gdm3 
 Thanks for your help

**Comment by Rox-** [comment]
Yeah, i do not want to update kernel to not break modules since it is working at the time.
Hope this will get fixed in future.

**Comment by Rox-** [comment]
I decided to give it a shot, i installed newest kernel 4.20.13 and it is still working as it should with lightdm.
18.10, 4.20.13, nvidia-415. Connected 2 displays using type c and HDMI.

**Comment by kfechter** [comment]
Cool. Im updating the guide to not do the kernel upgrade part since that seems to cause all sorts of issues.

**Comment by kfechter** [comment]
for anyone still having the issues, could you try the second solution in the accepted answer?

https://devtalk.nvidia.com/default/topic/1044770/hdmi-output-missing-in-xrandr-command-and-external-monitor-does-not-work/

**Comment by naaada06** [comment]
> for anyone still having the issues, could you try the second solution in the accepted answer?
> 
> https://devtalk.nvidia.com/default/topic/1044770/hdmi-output-missing-in-xrandr-command-and-external-monitor-does-not-work/

same issue here on a fresh install of 18.04.3, with nvidia-430 drivers and solved with that!
thanks!

**Comment by RobertRozic** [comment]
UPDATE

Right now i am using:

- 19.04
- 5.3.15 kernel
- Nvidia 440 drivers
- GMD3

External displays working correctly
